adam_beta1: 0.9
adam_beta2: 0.999
base_model_path: ashaar-from-scratch-with-spaces-no-tatweel-epochs-75
batch_size: 64
data_directory: data
data_separator: '|'
data_type: CA_MSA
device: cuda
diacritics_separator: '*'
error_rates_n_batches: 10000
evaluate_frequency: 50000000
evaluate_with_error_rates_frequency: 1000
freeze: true
is_data_preprocessed: false
learning_rate: 0.001
load_test_data: false
load_training_data: true
load_validation_data: true
log_directory: logs/log_dir_cls_5_test
max_eval_batches: -1
max_len: 600
max_sen_len: 256
max_steps: 5000
model_save_frequency: 5000
n_layer: 5
n_predicted_text_tensorboard: 10
n_steps_avg_losses:
- 100
- 500
- 1000
- 5000
n_test_examples: null
n_training_examples: null
n_validation_examples: null
optimizer_type: Adam
session_name: base
test_file_name: test.csv
test_model_path: null
text_cleaner: valid_arabic_cleaners
text_encoder: ArabicEncoderWithStartSymbol
train_plotting_frequency: 50000000
train_resume_model_path: null
use_decay: true
use_lstm: false
use_mixed_precision: false
weight_decay: 0.0
